#-----------------------
# IMPORTANTE: Los valores de los parametros de los ejercicio?_test deben ajustarse.
# Se asume que los ficheros fuente se llaman ejercicio1.c, ejercicio2.c,...,ordenar.h
#-----------------------

CC = gcc -ansi -pedantic -O3
CFLAGS = -Wall
EXE = ejercicio1 ejercicio2
all : $(EXE)

.PHONY : clean
clean :
	rm -f *.o core $(EXE)

$(EXE) : % : %.o ordenacion.o tiempos.o permutaciones.o ordenacion_examen.o busqueda.o
	@echo "#---------------------------"
	@echo "# Generando $@ "
	@echo "# Depende de $^"
	@echo "# Ha cambiado $<"
	$(CC) $(CFLAGS) -o $@ $@.o ordenacion.o tiempos.o permutaciones.o ordenacion_examen.o busqueda.o

permutaciones.o : permutaciones.c permutaciones.h
	@echo "#---------------------------"
	@echo "# Generando $@"
	@echo "# Depende de $^"
	@echo "# Ha cambiado $<"
	$(CC) $(CFLAGS) -c $<

ordenacion.o : ordenacion.c ordenacion.h
	@echo "#---------------------------"
	@echo "# Generando $@"
	@echo "# Depende de $^"
	@echo "# Ha cambiado $<"
	$(CC) $(CFLAGS) -c $<

busqueda.o : busqueda.c busqueda.h
	@echo "#---------------------------"
	@echo "# Generando $@"
	@echo "# Depende de $^"
	@echo "# Ha cambiado $<"
	$(CC) $(CFLAGS) -c $<

ordenacion_examen.o : ordenacion_examen.c ordenacion.h ordenacion_examen.h
	@echo "#---------------------------"
	@echo "# Generando $@"
	@echo "# Depende de $^"
	@echo "# Ha cambiado $<"
	$(CC) $(CFLAGS) -c $<

tiempos.o : tiempos.c tiempos.h
	@echo "#---------------------------"
	@echo "# Generando $@"
	@echo "# Depende de $^"
	@echo "# Ha cambiado $<"
	$(CC) $(CFLAGS) -c $<
	
ejercicio1_test:
	@echo Ejecutando ejercicio1
	@./ejercicio1 -num_min 1000 -num_max 10000, -incr 1000 -numP 1000 -L 100 -fichSalida iq100.log
	@./ejercicio1 -num_min 1000 -num_max 10000, -incr 1000 -numP 1000 -L 200 -fichSalida iq200.log
	@./ejercicio1 -num_min 1000 -num_max 10000, -incr 1000 -numP 1000 -L 300 -fichSalida iq300.log
	@./ejercicio1 -num_min 1000 -num_max 10000, -incr 1000 -numP 1000 -L 400 -fichSalida iq400.log

ejercicio2_test:
	@echo Ejecutando ejercicio2
	@./ejercicio2 -num_min 1000 -num_max 10000, -incr 1000 -numP 1000 -fichSalida qs.log
